# Change these first
owner: upptime # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Github psbadge API server
    url: https://psbadge.herokuapp.com/cf/CuteWisp
  - name: Atcoder User API server
    url: https://atcoder-api.herokuapp.com/user/CuteWisp
  - name: Blog
    url: https://blog.cutewisp.com

status-website:
  baseUrl: /repo # where "repo" is your repository name
  name: Cutewisp Status Website

