# Change these first
owner: upptime # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Cutewisp 
    url: https://cutewisp.com
  - name: Github psbadge API server
    url: https://api.cutewisp.com/api/ac/CuteWisp
  - name: Code server
    url: https://code.cutewisp.com/
  - name: Blog
    url: https://blog.cutewisp.com

status-website:
  baseUrl: /repo # where "repo" is your repository name
  name: Cutewisp Status Website

